//! Top-level transpilation entry point.
//!
//! Orchestrates: parse -> resolve symbols -> generate Rust code.

use crate::codegen::data_gen::generate_working_storage;
use crate::codegen::proc_gen::generate_procedure_division;
use crate::codegen::rust_writer::RustWriter;
use crate::error::Result;
use crate::parser::parse_cobol;

/// Transpile COBOL source code to Rust source code.
///
/// Takes raw COBOL source (fixed or free format) and returns
/// a complete Rust source file that depends on `cobol_runtime::prelude::*`.
///
/// # Errors
///
/// Returns `TranspileError` if parsing or code generation fails.
pub fn transpile(source: &str) -> Result<String> {
    let program = parse_cobol(source)?;
    let mut w = RustWriter::new();

    // File header
    w.line("//! Auto-generated Rust code from COBOL source.");
    w.line("//!");
    w.line(&format!(
        "//! Program: {}",
        program.program_id
    ));
    w.line("//! Generated by cobol-transpiler.");
    w.blank_line();
    w.line("#![allow(unused_imports, unused_variables, non_snake_case)]");
    w.blank_line();
    w.line("use cobol_runtime::prelude::*;");
    w.line("use rust_decimal_macros::dec;");
    w.blank_line();

    // Generate WorkingStorage struct
    if let Some(ref data_div) = program.data_division {
        generate_working_storage(&mut w, &data_div.working_storage);
        w.blank_line();
    }

    // Generate ProgramContext struct
    w.line("/// Runtime context for the COBOL program.");
    w.open_block("pub struct ProgramContext {");
    w.line("pub config: RuntimeConfig,");
    w.line("pub return_code: i32,");
    w.close_block("}");
    w.blank_line();

    w.open_block("impl ProgramContext {");
    w.open_block("pub fn new() -> Self {");
    w.open_block("Self {");
    w.line("config: RuntimeConfig::default(),");
    w.line("return_code: 0,");
    w.close_block("}");
    w.close_block("}");
    w.blank_line();

    w.open_block("pub fn stop_run(&self) {");
    w.line("std::process::exit(self.return_code);");
    w.close_block("}");
    w.blank_line();

    w.open_block("pub fn goback(&self) {");
    w.line("// GOBACK returns control to caller");
    w.close_block("}");
    w.blank_line();

    w.close_block("}");
    w.blank_line();

    // Generate procedure division
    if let Some(ref proc_div) = program.procedure_division {
        generate_procedure_division(&mut w, proc_div);
        w.blank_line();
    }

    // Generate main function
    w.open_block("fn main() {");
    w.line("let mut ws = WorkingStorage::new();");
    w.line("let mut ctx = ProgramContext::new();");
    w.line("run(&mut ws, &mut ctx);");
    w.close_block("}");

    Ok(w.finish())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn transpile_hello_world() {
        let source = concat!(
            "IDENTIFICATION DIVISION.\n",
            "PROGRAM-ID. HELLO.\n",
            "DATA DIVISION.\n",
            "WORKING-STORAGE SECTION.\n",
            "01  WS-NAME PIC X(20) VALUE 'WORLD'.\n",
            "PROCEDURE DIVISION.\n",
            "MAIN-PARA.\n",
            "    DISPLAY 'HELLO ' WS-NAME.\n",
            "    STOP RUN.\n",
        );

        let result = transpile(source);
        assert!(result.is_ok(), "transpile failed: {result:?}");
        let rust_code = result.unwrap();

        // Verify structure
        assert!(rust_code.contains("use cobol_runtime::prelude::*;"));
        assert!(rust_code.contains("pub struct WorkingStorage"));
        assert!(rust_code.contains("fn main()"));
        assert!(rust_code.contains("WorkingStorage::new()"));
        assert!(rust_code.contains("print!") || rust_code.contains("println!"));
        assert!(rust_code.contains("ctx.stop_run()"));
    }

    #[test]
    fn transpile_arithmetic() {
        let source = concat!(
            "IDENTIFICATION DIVISION.\n",
            "PROGRAM-ID. ARITH.\n",
            "DATA DIVISION.\n",
            "WORKING-STORAGE SECTION.\n",
            "01  WS-A PIC 9(5) VALUE 10.\n",
            "01  WS-B PIC 9(5) VALUE 20.\n",
            "01  WS-C PIC 9(5).\n",
            "PROCEDURE DIVISION.\n",
            "MAIN-PARA.\n",
            "    ADD WS-A TO WS-B.\n",
            "    MOVE WS-B TO WS-C.\n",
            "    DISPLAY WS-C.\n",
            "    STOP RUN.\n",
        );

        let result = transpile(source);
        assert!(result.is_ok(), "transpile failed: {result:?}");
        let rust_code = result.unwrap();

        assert!(rust_code.contains("cobol_add"));
        assert!(rust_code.contains("cobol_move"));
    }

    #[test]
    fn transpile_if_else() {
        let source = concat!(
            "IDENTIFICATION DIVISION.\n",
            "PROGRAM-ID. TESTIF.\n",
            "DATA DIVISION.\n",
            "WORKING-STORAGE SECTION.\n",
            "01  WS-X PIC 9(3) VALUE 5.\n",
            "PROCEDURE DIVISION.\n",
            "MAIN-PARA.\n",
            "    IF WS-X > 0\n",
            "        DISPLAY 'POSITIVE'\n",
            "    ELSE\n",
            "        DISPLAY 'NOT POSITIVE'\n",
            "    END-IF.\n",
            "    STOP RUN.\n",
        );

        let result = transpile(source);
        assert!(result.is_ok(), "transpile failed: {result:?}");
        let rust_code = result.unwrap();

        assert!(rust_code.contains("if "));
        assert!(rust_code.contains("} else {"));
    }

    #[test]
    fn transpile_perform() {
        let source = concat!(
            "IDENTIFICATION DIVISION.\n",
            "PROGRAM-ID. TESTPERF.\n",
            "DATA DIVISION.\n",
            "WORKING-STORAGE SECTION.\n",
            "01  WS-I PIC 9(3).\n",
            "PROCEDURE DIVISION.\n",
            "MAIN-PARA.\n",
            "    PERFORM WORK-PARA.\n",
            "    STOP RUN.\n",
            "WORK-PARA.\n",
            "    DISPLAY 'WORKING'.\n",
        );

        let result = transpile(source);
        assert!(result.is_ok(), "transpile failed: {result:?}");
        let rust_code = result.unwrap();

        assert!(rust_code.contains("work_para(ws, ctx);"));
        assert!(rust_code.contains("fn work_para("));
    }
}
